define({
	"AddressHelp": "This is the physical address of your Hub (optional).",
	"AddressLookupFailure": "Unable to find this address. You may manually enter the latitude and longitude below and/or click Next to use the address as is.",
	"AddressPlaceholder": "Street, City, State Zip",
	"Complete": "Complete",
	"CompleteWelcome": "Congratulations! Your new Hobson Hub is ready to use. Click the button below to go to the Hub management console. Note: You will need to enter the password you just set.",
	"ConfigurationSaveError": "Error saving configuration. Check that your Hobson Hub is running.",
	"Email": "Email",
	"EmailConfigSaveError": "An error occurred saving the e-mail configuration.",
	"EmailWelcome": "You're almost there. Here's where we set up your e-mail. This is optional but doing so allows you to receive mail notifications from Hobson.",
	"Gmail": "Gmail",
	"GotoConsole": "Management console",
	"HubAddress": "Hub address",
	"HubNickname": "Hub nickname",
	"Latitude": "Latitude",
	"LoadingPlugins": "Loading plugins...",
	"Longitude": "Longitude",
	"LookingUpAddress": "Looking up your address...",
	"LookupFailed": "Lookup failed",
	"MailPasswordHelp": "Enter the password used to login to the mail server. Leave blank to keep the current password.",
	"MailSenderHelp": "Enter the reply address for sent e-mails.",
	"MailServerHelp": "Enter the host name of IP address of your mail server.",
	"MailServerSecure": "Use secure connection (SSL/TLS)",
	"MailUserHelp": "Enter the user name used to login to the mail server.",
	"Next": "Next",
	"NicknameHelp": "This is a short name we'll use to refer to your Hub throughout the Hobson experience.",
	"NicknameRequired": "Nickname is required",
	"None": "None",
	"Other": "Other",
	"Password": "Password",
	"PasswordGenericError": "An error occurred setting the Hub password. See the log for details.",
	"PasswordMatchError": "The passwords do not match.",
	"PasswordMissingError": "You must enter a password.",
	"PasswordHelp": "8-14 characters with upper and lower case, one number and one special character.",
	"PasswordWelcome": "Here's where we set up a password for your new Hub. You will need this whenever you use the Hobson web console.",
	"Plugins": "Plugins",
	"PluginSelectionPrompt": "Select one or more plugins you want to start with by clicking on them.",
	"PluginsWelcome": "Here's where you'll choose your plugins. Plugins teach Hobson to talk with different smart devices. Don't worry if you don't install them all now &mdash; you can add more later.",
	"RepeatPassword": "Repeat password",
	"RepeatPasswordHelp": "Enter the same password again.",
	"Send": "Send",
	"SenderAddress": "Sender address",
	"SendTestMessage": "Send test message",
	"ServerHostname": "Server Hostname",
	"ServerType": "Server type",
    "SkipSetupPrompt": "Hint: Don't want to run through the configuration wizard? <a href=\"/console/index.html\">Click here</a> to start using Hobson immediately (the default password is \"password\").",
	"Start": "Start",
	"StartWelcome": "Welcome to Hobson! You'll need a few minutes to get rolling. Start by entering a nickname and address for your Hub. We'll use this as a unique identifier.",
	"TestMessageServerMissing": "You must choose a server to send a test message.",
	"TestMessageSuccessful": "Test message was sent successfully.",
	"TestMessageFailure": "An error occurred sending the test message.",
	"TestMessagePasswordMissing": "You must enter a password to send a test message.",
	"UploadPrompt": "Upload an image of your home to use on the dashboard (optional).",
	"UserName": "User name",
	"WizardGenericError": "An error has occurred running the configuration wizard. Check the log file for details.",
	"WizardPasswordError": "The configuration wizard cannot be run once the default password has been changed. <a href=\"/console\">Click here</a> to go to the web console.",
	"WizardTimeoutError": "The setup wizard has timed out. <a href=\"/\">Click here </a> to start over."
});
