define({
	"AddressHelp": "Esta es la dirección física de su Hub (opcional).",
	"AddressLookupFailure": "No se ha podido encontrar esta dirección. Puede introducir manualmente la latitud y longitud inferior y / o en Siguiente para utilizar la dirección como es.",
	"AddressPlaceholder": "Calle, Ciudad, Estado, Código Postal",
	"Complete": "Terminado",
	"CompleteWelcome": "¡Enhorabuena! Su nuevo Hobson Hub está listo para usar. Haga clic en el botón de abajo para ir a la consola de administración de concentradores. Nota: Es muy probable que me pida un nombre de usuario y contraseña.",
	"Email": "Correo",
	"EmailWelcome": "Ya casi ha terminado. Aquí es donde armaremos su e -mail. Si lo hace, le permitirá recibir notificaciones de Hobson.",
	"Gmail": "Gmail",
	"GotoConsole": "Consola de administración",
	"HubAddress": "Dirección hub",
	"HubNickname": "Apodo hub",
	"Latitude": "Latitud",
	"Longitude": "Longitud",
	"LookingUpAddress": "Mirando hacia arriba su dirección...",
	"MailPasswordHelp": "Introduzca la contraseña utilizada para iniciar sesión en el servidor de correo.",
	"MailSenderHelp": "Introduzca la contraseña utilizada para iniciar sesión en el servidor de correo.",
	"MailServerHelp": "Introduzca el nombre de host de la dirección IP de su servidor de correo.",
	"MailServerSecure": "Usar conexión segura (SSL/TLS)",
	"MailUserHelp": "Introduzca el nombre de usuario utilizado para iniciar sesión en el servidor de correo.",
	"Next": "Siguiente",
	"NicknameHelp": "Este es un nombre corto que usaremos para referirse a su Hub en toda la experiencia Hobson.",
	"None": "Ninguno",
	"Other": "Otro",
	"Password": "Contraseña",
	"PasswordHelp": "8-14 caracteres con mayúsculas y minúsculas, un número y un carácter especial.",
	"PasswordWelcome": "Aquí es donde hemos creado una contraseña para su Hub. Lo necesitará cada vez que utilice la consola web Hobson.",
	"Plugins": "Plugins",
	"PluginsWelcome": "Aquí es donde usted elige sus plugins. Plugins permitir Hobson hablar con todo el hardware diferente que tiene. Siempre se puede añadir más tarde.",
	"RepeatPassword": "Repita la contraseña",
	"RepeatPasswordHelp": "Confirme la misma contraseña.",
	"SenderAddress": "Enviar dirección",
	"SendTestMessage": "Enviar mensaje de prueba",
	"ServerHostname": "Nombre de host del servidor",
	"ServerType": "Tipo de servidor",
	"Start": "Comienzo",
	"StartWelcome": "¡Bienvenido a Hobson! Usted necesitará unos minutos para conseguir el balanceo. Comience por indicar un apodo y dirección para su Hub. Vamos a utilizar esto como un identificador único.",
	"UploadPrompt": "Sube una imagen de su casa para usar en el salpicadero (opcional).",
	"UserName": "Nombre de usuario"
});